#!/bin/bash

set -e

echo ""
echo "Downloading latest version of the dotnet-install.sh script..."

mkdir -p $HOME/Downloads
curl -fsSL https://dot.net/v1/dotnet-install.sh -o $HOME/Downloads/dotnet-install.sh
chmod +x $HOME/Downloads/dotnet-install.sh

echo "Installing .NET 8 SDK..."
"$HOME"/Downloads/dotnet-install.sh --channel 8.0 > /dev/null
echo "✅ .NET 8 SDK installed!"

echo ""
echo "Installing .NET 10 SDK..."
"$HOME"/Downloads/dotnet-install.sh --channel 10.0 > /dev/null
echo "✅ .NET 10 SDK installed!"

echo '
# THIS FILE IS AUTO-GENERATED BY THE UBUNTU-SETUP SCRIPT
# DO NOT MODIFY DIRECTLY

# .NET Core SDK
# Installed via the https://dot.net/v1/dotnet-install.sh script
export DOTNET_ROOT="$HOME/.dotnet"
export PATH="$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools"
' > "$HOME/.bash_sources/dotnet_source.sh"

echo "✅ .NET SDK installation complete!"
