#!/bin/bash

set -e

echo "Installing OpenJDK 21..."
sudo apt-get install -y openjdk-21-jdk > /dev/null
echo "✅ OpenJDK 21 installed!"

# Find JAVA_HOME
JAVA_HOME=$(readlink -f $(command -v java) | sed "s:/bin/java::")

echo '
# THIS FILE IS AUTO-GENERATED BY THE UBUNTU-SETUP SCRIPT
# DO NOT MODIFY DIRECTLY

# Java SDK
# Installed via "apt install -y openjdk-21-jdk"
export JAVA_HOME="'$JAVA_HOME'"
export PATH="$PATH:$JAVA_HOME/bin"
' > "$HOME/.bash_sources/java_source.sh"

echo "✅ Java installation complete!"
